version: "3.9"
networks:
  common_network:
    driver: bridge
volumes:
  db_data:
    driver: local
services:
  db:
    container_name: db
    image: postgres:13-alpine
    networks:
      - common_network
    restart: always
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER}
    volumes:
      - db_data:/var/lib/postgresql/data
  dish:
    container_name: dish
    image: registry.digitalocean.com/anhdau185/dish-api:latest
    networks:
      - common_network
    restart: always
    ports:
      - "${PORT}:5000"
    depends_on:
      - db
    links:
      - db
